# Generated by Django 2.2.24 on 2021-08-16 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangocms_versioning', '0015_version_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentExpiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(verbose_name='expiry date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='expired by')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djangocms_versioning.Version', verbose_name='version')),
            ],
            options={
                'verbose_name': 'Content Expiry',
                'verbose_name_plural': 'Content Expiry',
            },
        ),
    ]
