# Generated by Django 2.2.24 on 2021-09-24 08:13

from django.db import migrations, models
import django.db.models.deletion
import djangocms_content_expiry.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djangocms_content_expiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultContentExpiryConfiguration',
            fields=[
                ('content_type', models.OneToOneField(limit_choices_to=djangocms_content_expiry.models._limit_content_type_choices, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contenttypes.ContentType', verbose_name='content type')),
                ('duration', models.IntegerField(default=12, help_text='Duration in months')),
            ],
            options={
                'verbose_name': 'Content Type Configuration',
                'verbose_name_plural': 'Content Type Configuration',
            },
        ),
    ]
