# Generated by Django 2.2.24 on 2022-05-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('djangocms_content_expiry', '0002_defaultcontentexpiryconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentexpiry',
            name='compliance_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
