# Generated by Django 3.2.14 on 2022-09-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_content_expiry', '0003_contentexpiry_compliance_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentexpiry',
            name='compliance_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
